name: CI/CD for Django based App

on:
  push:
    branches:
      - master
  pull_request:    ## need to review
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    
    - name: Python Environment Setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip


    # - name: Setup venv for Python
    #   run: |
    #     python -m venv venv
    #     source venv/bin/activate

    - name: Install Dependencies
      run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

   

    

  #   ## caching dependencies

  #   - name: Cache Pip Dependencies
  #     uses: actions/cache@v3
  #     with:
  #       path: ~/.cache/pip
  #       key: ${{ runner.os }}-pip-{{ $hashFiles('**/requirements.txt') }}
  #       restore-keys: |
  #        ${{ runner.os }}-pip-

  #   # - name: Run Tests and generate coverage
  #   #   run: |
  #   #     pip install coverage
  #   #     coverage run -m pytest

  security:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - run: echo "second job complete"

